### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by flycoolman** [netconf-wg/list-pagination-nc#4]
1. Updates needs to add RFC8526
Updates:6241 (if approved)
vs.
This document updates [RFC6241] and [RFC8526], as described in Section 2.

2. Typo "larger then" should be "larger than"
If the "offset" query parameter value supplied is larger then the number of instances in the list or leaf-list target resource, the <rpc-error> MUST contain error-app-tag with value "offset-out-of-range".

3. to be added after further review

**Comment by kwatsen** [comment]
The first issue was/is a non-issue (already done).

The typo (2nd issue) is fixed.
